
#define _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_DEPRECATE
#define _CRT_NONSTDC_NO_DEPRECATE

#define CODEC_TYPE CODEC_TYPE_CHACHA20
#define SQLITE_HAS_CODEC 1
#define SQLITE_THREADSAFE 1
#define SQLITE_MAX_ATTACHED 10
#define SQLITE_SOUNDEX 1
#define SQLITE_ENABLE_COLUMN_METADATA 1
#define SQLITE_SECURE_DELETE 1
#define SQLITE_ENABLE_FTS3 1
#define SQLITE_ENABLE_FTS3_PARENTHESIS 1
#define SQLITE_ENABLE_FTS4 1
#define SQLITE_ENABLE_FTS5 1
#define SQLITE_ENABLE_JSON1 1
#define SQLITE_ENABLE_RTREE 1
#define SQLITE_ENABLE_GEOPOLY 1
#define SQLITE_CORE 1
#define SQLITE_ENABLE_EXTFUNC 1
#define SQLITE_ENABLE_CSV 1
#define SQLITE_ENABLE_SHA3 1
#define SQLITE_ENABLE_CARRAY 1
#define SQLITE_ENABLE_FILEIO 1
#define SQLITE_ENABLE_SERIES 1
#define SQLITE_ENABLE_UUID 1
#define SQLITE_TEMP_STORE 2
#define SQLITE_USE_URI 1
#define SQLITE_USER_AUTHENTICATION 1

